// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvt0yyxlTzWpb-gKQ5iSce_JrgS97QO5I',
    appId: '1:790464644403:web:fc23735689ef1506f1ea46',
    messagingSenderId: '790464644403',
    projectId: 'crud-a492d',
    authDomain: 'crud-a492d.firebaseapp.com',
    storageBucket: 'crud-a492d.appspot.com',
    measurementId: 'G-RCQBJCL5EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx0LWSrVwiPqrSgaPMretD7KjuSpLF-OY',
    appId: '1:790464644403:android:d577555ad82a0ba6f1ea46',
    messagingSenderId: '790464644403',
    projectId: 'crud-a492d',
    storageBucket: 'crud-a492d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaszBcFsYqRdX94oGBz9wCnfTFEfIPCkI',
    appId: '1:790464644403:ios:b8769ca3c3fbd9e8f1ea46',
    messagingSenderId: '790464644403',
    projectId: 'crud-a492d',
    storageBucket: 'crud-a492d.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaszBcFsYqRdX94oGBz9wCnfTFEfIPCkI',
    appId: '1:790464644403:ios:1d811e9ffd396727f1ea46',
    messagingSenderId: '790464644403',
    projectId: 'crud-a492d',
    storageBucket: 'crud-a492d.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
